sudo: true
dist: trusty
language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
install:
  - "cpanm --installdeps --notest ."
services:
  - mysql
  - memcached
  - elasticsearch
addons:
  apt:
    packages:
    - libxml2-dev
    - libexpat1-dev
    - libv8-3.14-dev
    - libgd-dev
addons:
  hosts:
    - helptasker.net
env:
  - "MOJO_TEST_TRAVIS=1"
before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.2/elasticsearch-2.3.2.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.2.deb && sudo service elasticsearch restart
before_script:
  - mysql -e 'create database IF NOT EXISTS test;' -uroot
after_script:
  - mysql -e 'drop database test;' -uroot

# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
