sudo: true
dist: trusty
language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
install:
  - "cpanm --installdeps --notest ."
services:
  - memcached
  - elasticsearch
addons:
  apt:
    packages:
    - libxml2-dev
    - libexpat1-dev
    - libv8-3.14-dev
    - libgd-dev
addons:
  hosts:
    - helptasker.net
env:
  - "MOJO_TEST_TRAVIS=1"
before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.2/elasticsearch-2.3.2.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.2.deb && sudo service elasticsearch restart
  - export MYSQL_APT_CONFIG_FILE=mysql-apt-config_0.7.2-1_all.deb
  - wget http://dev.mysql.com/get/$MYSQL_APT_CONFIG_FILE
  - sudo dpkg -i $MYSQL_APT_CONFIG_FILE
  - sudo apt-get -y update
  - sudo apt-get install -y mysql-community-client mysql-community-server
before_script:
  - mysql --version
  - sudo mysql -u root -e 'create database test;'
after_script:
  - sudo mysql -u root -e 'drop database test;'

# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
