sudo: required
dist: trusty
language: perl
perl:
  - "5.21"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
install:
  - "cpanm -n Mojolicious DBI DBD::mysql"
  - "cpanm --installdeps --notest ."
services:
  - mysql
addons:
  hosts:
    - helptasker.net
  packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
env:
  - "MOJO_TEST_TRAVIS=1"
before_script:
  - mysql -e "create database IF NOT EXISTS test;"
after_script:
  - mysql -e 'drop database test;'

