sudo: true
language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
install:
  - "cpanm -n Mojolicious DBI DBD::mysql"
  - "cpanm --installdeps --notest ."
services:
  - mysql
  - memcached
  - elasticsearch
addons:
  apt:
    packages:
    - libxml2-dev
    - libexpat1-dev
    - libv8-3.14-dev
    - libgd-dev
addons:
  hosts:
    - helptasker.net
env:
  - "MOJO_TEST_TRAVIS=1"
before_script:
  - mysql -e 'create database IF NOT EXISTS test;' -uroot
after_script:
  - mysql -e 'drop database test;' -uroot

# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
