sudo: required
language: perl
perl:
  - "5.21"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
install:
  - "cpanm -n Mojolicious DBI DBD::mysql"
  - "cpanm --installdeps --notest ."
services:
  - mysql
  - memcached
  - elasticsearch
addons:
  hosts:
    - helptasker.net
env:
  - "MOJO_TEST_TRAVIS=1"
before_script:
  - mysql -e 'create database IF NOT EXISTS test;' -uroot
after_script:
  - mysql -e 'drop database test;' -uroot

