#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib 'lib';

BEGIN {
    unshift @INC, "$FindBin::Bin/../lib";
    unshift @INC, "$FindBin::Bin/../";
}

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('Api');
