#!/usr/bin/env perl
use strict;
use warnings;
use Mojo::Server::Morbo;
use FindBin;

$ENV{'MOJO_LISTEN'} = 'http://[::]:49049';

BEGIN {
	unshift @INC, "$FindBin::Bin/../lib"
}

my @dir_watch = ();
push(@dir_watch, "$FindBin::Bin/../$_/") for(qw/lib templates public/);

my $morbo = Mojo::Server::Morbo->new;
$morbo->watch(\@dir_watch);
$morbo->run($FindBin::Bin.'/api');

